name: Build Master Branch

on: [push, pull_request]

jobs:
  build-host:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .

    steps:
    - name: Checkout source code
      uses: actions/checkout@v3

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable

    - name: Install Rust targets
      run: rustup target add x86_64-unknown-linux-gnu

    - name: Build
      run: cargo build --release

    - name: Test
      run: |
        sudo apt install -y iperf3
        sudo tests/iperf.sh

  build-android:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./android-app

    steps:
    - name: Checkout source code
      uses: actions/checkout@v3

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable

    - name: Update Rust
      run: rustup update

    - name: Install Rust targets
      run: rustup target add aarch64-linux-android armv7-linux-androideabi i686-linux-android x86_64-linux-android

    - uses: nttld/setup-ndk@v1.4.2
      id: setup-ndk
      with:
        ndk-version: r25c
        link-to-sdk: true

    #- name: Set up Android NDK
    #  run: |
    #    echo $ANDROID_SDK_ROOT
    #    $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager --install "ndk;26.1.10909125"
    #    export ANDROID_NDK_ROOT=$ANDROID_SDK_ROOT/ndk/26.1.10909125

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x ./gradlew

    - name: Build with Gradle
      run: ./gradlew clean build
